SELECT SUM(SALARY) SOMA, MIN(SALARY) MENOR, MAX(SALARY) MAIOR, TRUNC(AVG(SALARY),2) MEDIA
FROM EMPLOYEES;

SELECT SUM(E.SALARY) SOMA, MIN(E.SALARY) MENOR, 
    MAX(E.SALARY) MAIOR, TRUNC(AVG(E.SALARY),2) MEDIA
FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    USING(DEPARTMENT_ID)
WHERE UPPER(D.DEPARTMENT_NAME) = UPPER('Sales');

SELECT SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80
ORDER BY SALARY ASC;

SELECT MIN(HIRE_DATE) ANTIGA, MAX(HIRE_DATE) RECENTE
FROM EMPLOYEES;

SELECT COUNT(*)
FROM EMPLOYEES;

SELECT COUNT(*)
FROM EMPLOYEES
    INNER JOIN DEPARTMENTS D
    USING(DEPARTMENT_ID)
WHERE UPPER(D.DEPARTMENT_NAME) = UPPER('Marketing');

SELECT * FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'Marketing';

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;

SELECT EMPLOYEE_ID, COMMISSION_PCT
FROM EMPLOYEES
ORDER BY COMMISSION_PCT ASC;

SELECT COUNT(COMMISSION_PCT)
FROM EMPLOYEES;

SELECT COUNT(DISTINCT SALARY)
FROM EMPLOYEES;

SELECT TRUNC(AVG(COMMISSION_PCT),2) "MEDIA %"
FROM EMPLOYEES;

SELECT AVG(NVL(COMMISSION_PCT,0))
FROM EMPLOYEES;

-- NOME DE EMPREGADO E NOME DE DPTO QUE ELE GERENCIA
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
    LEFT OUTER JOIN DEPARTMENTS D
    ON (D.MANAGER_ID = E.EMPLOYEE_ID);

SELECT E.LAST_NAME, NVL(D.DEPARTMENT_NAME, 'NENHUM DPTO')
FROM EMPLOYEES E
    LEFT OUTER JOIN DEPARTMENTS D
    ON (D.MANAGER_ID = E.EMPLOYEE_ID);
    
SELECT ROWNUM, LAST_NAME
FROM EMPLOYEES
WHERE ROWNUM < 11
ORDER BY LAST_NAME;

SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, TRUNC(AVG(SALARY),2) MEDIA_SALARIO
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY MEDIA_SALARIO DESC, DEPARTMENT_ID ASC;

SELECT DEPARTMENT_ID, SUM(SALARY) SOMA, MIN(SALARY) MENOR, MAX(SALARY) MAIOR, TRUNC(AVG(SALARY),2) MEDIA
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID ASC;

SELECT JOB_ID, COUNT(*), MAX(SALARY), TRUNC(AVG(SALARY),2)
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY JOB_ID ASC;

SELECT D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID)
FROM DEPARTMENTS D
    INNER JOIN EMPLOYEES E
    USING(DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME
ORDER BY D.DEPARTMENT_NAME;

SELECT L.CITY, COUNT(E.EMPLOYEE_ID)
FROM LOCATIONS L
    LEFT OUTER JOIN DEPARTMENTS D
    USING(LOCATION_ID)
    INNER JOIN EMPLOYEES E
    USING(DEPARTMENT_ID)
GROUP BY L.CITY
ORDER BY L.CITY;
    
SELECT L.CITY, COUNT(*) QUANTIDADE
FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    USING (DEPARTMENT_ID)
    INNER JOIN LOCATIONS L
    USING (LOCATION_ID)
GROUP BY L.CITY
ORDER BY QUANTIDADE DESC;

SELECT L.CITY, D.DEPARTMENT_ID, E.EMPLOYEE_ID
FROM LOCATIONS L, DEPARTMENTS D, EMPLOYEES E
WHERE L.LOCATION_ID = D.LOCATION_ID 
AND D.DEPARTMENT_ID = E.DEPARTMENT_ID
ORDER BY L.CITY;

SELECT DEPARTMENT_ID, JOB_ID, TRUNC(AVG(SALARY),2) MEDIA
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, TRUNC(AVG(SALARY),2) MEDIA
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) > 8000
ORDER BY DEPARTMENT_ID;

SELECT D.DEPARTMENT_NAME, COUNT(*), TRUNC(AVG(E.SALARY),2) MEDIA
FROM DEPARTMENTS D
    INNER JOIN EMPLOYEES E
    USING(DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID) > 5
ORDER BY DEPARTMENT_NAME;

SELECT DEPARTMENT_ID, COUNT(*), TRUNC(AVG(SALARY),2)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 5
ORDER BY COUNT(*);

SELECT L.CITY, TRUNC(AVG(SALARY),2)
FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS
    USING (DEPARTMENT_ID)
    INNER JOIN LOCATIONS L
    USING (LOCATION_ID)
WHERE COUNTRY_ID = 'US'
GROUP BY L.CITY
HAVING AVG(SALARY) > 5000
ORDER BY CITY;

SELECT L.CITY, TRUNC(AVG(SALARY),2)
FROM EMPLOYEES E
    INNER JOIN DEPARTMENTS D
    USING (DEPARTMENT_ID)
    INNER JOIN LOCATIONS L
    USING (LOCATION_ID)
WHERE L.COUNTRY_ID = 'US'
GROUP BY L.CITY
HAVING AVG(SALARY) > 5000;
